services:
  videocrypt-api:
    build:
      context: ..
      dockerfile: VideoCrypt.Image.Api/Dockerfile
    ports:
      - "7001:7003"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    network_mode: host

  videocrypt-main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    network_mode: host
